use std::io::{self, Write};

use crate::dot::{OutputCommand, OutputSymbol};

pub struct Gnu;

impl Gnu {
    pub fn print_function_name<W: Write + ?Sized>(
        writer: &mut W,
        symbol: &OutputSymbol,
        has_subtree: bool,
        print_as_tree: bool,
    ) -> io::Result<()> {
        write!(writer, "{}", symbol.name)?;

        if symbol
            .declaration
            .as_deref()
            .is_some_and(|decl| decl.contains('('))
        {
            write!(writer, "()")?;
        }

        if let Some(declaration) = &symbol.declaration {
            let source = symbol.source.as_deref().unwrap_or("?");
            let line = symbol.definition_line.unwrap_or_default();
            write!(writer, " <{} at {}:{}>", declaration, source, line)?;
        }

        if symbol.active {
            if let Some(line) = symbol.expand_line {
                write!(writer, " (recursive: see {})", line.saturating_sub(1))?;
            } else {
                write!(writer, " (recursive)")?;
            }
            return Ok(());
        }

        if !symbol.related_symbols.is_empty() {
            write!(writer, " (R)")?;
        }

        if !print_as_tree && has_subtree {
            write!(writer, ":")?;
        }

        Ok(())
    }

    pub fn print_symbol<W: Write + ?Sized>(
        writer: &mut W,
        line: i32,
        symbol: &mut OutputSymbol,
        brief_listing: bool,
        print_as_tree: bool,
    ) -> io::Result<bool> {
        let has_subtree = !symbol.related_symbols.is_empty();

        let level = if symbol.direct { 0 } else { 1 };
        for _ in 0..level {
            write!(writer, "    ")?;
        }

        Self::print_function_name(writer, symbol, has_subtree, print_as_tree)?;

        if brief_listing {
            if let Some(expand_line) = symbol.expand_line {
                write!(writer, " [see {}]", expand_line)?;
                return Ok(true);
            } else if has_subtree {
                symbol.expand_line = Some(line);
            }
        }

        Ok(false)
    }

    pub fn output_handler<W: Write + ?Sized>(
        writer: &mut W,
        command: OutputCommand,
        line: i32,
        text: Option<&str>,
        symbol: Option<&mut OutputSymbol>,
        emacs_option: bool,
        package_string: &str,
        brief_listing: bool,
        print_as_tree: bool,
    ) -> io::Result<bool> {
        match command {
            OutputCommand::Begin => {
                if emacs_option {
                    write!(
                        writer,
                        ";; This file is generated by {}. -*- cflow -*-",
                        package_string
                    )?;
                    writeln!(writer)?;
                }
                Ok(false)
            }
            OutputCommand::Newline => {
                writeln!(writer)?;
                Ok(false)
            }
            OutputCommand::Separator => {
                writeln!(writer)?;
                Ok(false)
            }
            OutputCommand::Text | OutputCommand::End | OutputCommand::Other => Ok(false),
            OutputCommand::Symbol => {
                let _ = text;
                if let Some(symbol) = symbol {
                    Self::print_symbol(writer, line, symbol, brief_listing, print_as_tree)
                } else {
                    Ok(false)
                }
            }
        }
    }
}
