use std::io::{self, Write};

pub struct Gnu;

#[derive(Clone, Debug)]
pub struct OutputSymbol<'a> {
    pub direct: bool,
    pub level: usize,
    pub last: bool,
    pub sym: &'a SymbolView<'a>,
}

#[derive(Clone, Debug, Default)]
pub struct SymbolView<'a> {
    pub name: &'a str,
    pub arity: i32,
    pub decl: Option<&'a str>,
    pub source: Option<&'a str>,
    pub def_line: Option<usize>,
    pub active: Option<usize>,
    pub recursive: bool,
    pub has_callee: bool,
    pub has_caller: bool,
    pub expand_line: Option<usize>,
}

#[derive(Debug)]
pub enum GnuCommand<'a> {
    Begin {
        emacs_mode: bool,
        package_string: &'a str,
    },
    Init,
    End,
    Separator,
    Newline,
    Text(&'a str),
    Symbol(&'a mut OutputSymbol<'a>),
}

impl Gnu {
    pub fn print_function_name<W: Write + ?Sized>(
        writer: &mut W,
        sym: &SymbolView<'_>,
        has_subtree: bool,
        print_as_tree: bool,
    ) -> io::Result<()> {
        write!(writer, "{}", sym.name)?;
        if sym.arity >= 0 {
            write!(writer, "()")?;
        }
        if let (Some(decl), Some(source), Some(def_line)) = (sym.decl, sym.source, sym.def_line) {
            write!(writer, " <{} at {}:{}>", decl, source, def_line)?;
        }
        if let Some(active) = sym.active {
            write!(writer, " (recursive: see {})", active.saturating_sub(1))?;
            return Ok(());
        }
        if sym.recursive {
            write!(writer, " (R)")?;
        }
        if !print_as_tree && has_subtree {
            write!(writer, ":")?;
        }
        Ok(())
    }

    pub fn print_symbol<W: Write + ?Sized>(
        writer: &mut W,
        line: usize,
        symbol: &mut OutputSymbol<'_>,
        brief_listing: bool,
        print_as_tree: bool,
    ) -> io::Result<bool> {
        Self::print_level(writer, symbol.level, symbol.last)?;
        let has_subtree = if symbol.direct {
            symbol.sym.has_callee
        } else {
            symbol.sym.has_caller
        };

        Self::print_function_name(writer, symbol.sym, has_subtree, print_as_tree)?;

        if brief_listing {
            if let Some(expand_line) = symbol.sym.expand_line {
                write!(writer, " [see {}]", expand_line)?;
                return Ok(true);
            }
        }

        let _ = line;
        Ok(false)
    }

    pub fn output_handler<W: Write + ?Sized>(
        &mut self,
        writer: &mut W,
        line: usize,
        command: GnuCommand<'_>,
        brief_listing: bool,
        print_as_tree: bool,
    ) -> io::Result<bool> {
        match command {
            GnuCommand::Begin {
                emacs_mode,
                package_string,
            } => {
                if emacs_mode {
                    write!(
                        writer,
                        ";; This file is generated by {}. -*- cflow -*-",
                        package_string
                    )?;
                    writeln!(writer)?;
                }
                Ok(false)
            }
            GnuCommand::Init | GnuCommand::End | GnuCommand::Separator => Ok(false),
            GnuCommand::Newline => {
                writeln!(writer)?;
                Ok(false)
            }
            GnuCommand::Text(text) => {
                write!(writer, "{}", text)?;
                Ok(false)
            }
            GnuCommand::Symbol(symbol) => {
                Self::print_symbol(writer, line, symbol, brief_listing, print_as_tree)
            }
        }
    }

    fn print_level<W: Write + ?Sized>(writer: &mut W, level: usize, _last: bool) -> io::Result<()> {
        for _ in 0..level {
            write!(writer, "    ")?;
        }
        Ok(())
    }
    }
