use std::env;
use std::fmt;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::Path;
use std::process::{Command, ExitCode};
use std::time::{SystemTime, UNIX_EPOCH};

const SIZE: usize = 4096;
const VERSION: &str = "shc-rust";
const SUBJECT: &str = "script encoder and C source generator";
const COPYRIGHT: &str = "Copyright";
const USAGE: &str = "Usage: shc -f script_file [options]";
const COPYING: &[&str] = &[
    "This is a Rust rewrite focused on the evidenced behavior of src/shc.c.",
    "It preserves the main CLI flow, byte processing, and code generation shape.",
];
const ABSTRACT: &[&str] = &[
    "shc reads a shell script, derives execution metadata,",
    "and writes a generated C source artifact plus optional build output.",
];
const HELP: &[&str] = &[
    "-e dd/mm/yyyy  expiration date",
    "-m message      mail address appended to expiration message",
    "-f file         source script file",
    "-i inline       interpreter inline option",
    "-x exec         interpreter exec option",
    "-l last         interpreter last option marker",
    "-o output       output binary path",
    "-r              relaxed mode",
    "-v              verbose",
    "-D              debug-exec",
    "-S              setuid",
    "-U              disable traceable",
    "-H              hardening",
    "-B              busybox on",
    "-2              mmap2 on",
    "-C              copyright",
    "-A              abstract",
    "-h              help",
];
const RTC: &[&str] = &[
    "",
    "/* Generated by Rust shc port */",
    "",
];
const SETUID_LINE: &str = "#define SETUID %d\n";
const DEBUGEXEC_LINE: &str = "#define DEBUGEXEC %d\n";
const TRACEABLE_LINE: &str = "#define TRACEABLE %d\n";
const HARDENING_LINE: &str = "#define HARDENING %d\n";
const BUSYBOXON_LINE: &str = "#define BUSYBOXON %d\n";
const MMAP2_LINE: &str = "#define MMAP2 %d\n";

#[derive(Debug)]
enum ShcError {
    Io(io::Error),
    InvalidArgs(String),
    InvalidData(String),
    ProcessFailed(String),
    EarlyExit(i32),
}

impl fmt::Display for ShcError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ShcError::Io(e) => write!(f, "{e}"),
            ShcError::InvalidArgs(s) => write!(f, "{s}"),
            ShcError::InvalidData(s) => write!(f, "{s}"),
            ShcError::ProcessFailed(s) => write!(f, "{s}"),
            ShcError::EarlyExit(code) => write!(f, "exit({code})"),
        }
    }
}

impl From<io::Error> for ShcError {
    fn from(value: io::Error) -> Self {
        ShcError::Io(value)
    }
}

#[derive(Clone)]
struct Provider {
    f: &'static str,
    s: &'static str,
    e: &'static str,
}

#[derive(Clone)]
struct ShellEntry {
    shll: &'static str,
    inlo: &'static str,
    xecc: &'static str,
    lsto: &'static str,
}

#[derive(Clone)]
struct Arc4State {
    indx: u8,
    jndx: u8,
    kndx: u8,
    stte: [u8; 256],
}

impl Default for Arc4State {
    fn default() -> Self {
        let mut s = Self {
            indx: 0,
            jndx: 0,
            kndx: 0,
            stte: [0; 256],
        };
        for (i, b) in s.stte.iter_mut().enumerate() {
            *b = i as u8;
        }
        s
    }
}

pub struct Shc {
    my_name: String,
    file: Option<String>,
    file2: Option<String>,
    mail: String,
    inlo: Option<String>,
    xecc: Option<String>,
    lsto: Option<String>,
    shll: Option<String>,
    opts: String,
    text: Option<Vec<u8>>,
    date: String,
    rlax: [u8; 1],
    verbose: u32,
    setuid_flag: i32,
    debugexec_flag: i32,
    traceable_flag: i32,
    hardening_flag: i32,
    busyboxon_flag: i32,
    mmap2_flag: i32,
    offset: usize,
    arc4: Arc4State,
    rand_state: u64,
    provider: Provider,
}

impl Default for Shc {
    fn default() -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0x9E37_79B9_7F4A_7C15);
        Self {
            my_name: "shc".to_string(),
            file: None,
            file2: None,
            mail: String::new(),
            inlo: None,
            xecc: None,
            lsto: None,
            shll: None,
            opts: String::new(),
            text: None,
            date: "0".to_string(),
            rlax: [0],
            verbose: 0,
            setuid_flag: 0,
            debugexec_flag: 0,
            traceable_flag: 1,
            hardening_flag: 0,
            busyboxon_flag: 0,
            mmap2_flag: 0,
            offset: 0,
            arc4: Arc4State::default(),
            rand_state: nanos ^ 0xA5A5_5A5A_D3C1_B2E7,
            provider: Provider {
                f: "Rust",
                s: "Port",
                e: "Project",
            },
        }
    }
}

impl Shc {
    fn shells_db() -> &'static [ShellEntry] {
        &[
            ShellEntry {
                shll: "sh",
                inlo: "-c",
                xecc: "-c",
                lsto: "--",
            },
            ShellEntry {
                shll: "bash",
                inlo: "-c",
                xecc: "-c",
                lsto: "--",
            },
            ShellEntry {
                shll: "dash",
                inlo: "-c",
                xecc: "-c",
                lsto: "--",
            },
            ShellEntry {
                shll: "ksh",
                inlo: "-c",
                xecc: "-c",
                lsto: "--",
            },
            ShellEntry {
                shll: "zsh",
                inlo: "-c",
                xecc: "-c",
                lsto: "--",
            },
        ]
    }

    fn render_define_i32(fmt: &str, value: i32) -> String {
        fmt.replacen("%d", &value.to_string(), 1)
    }

    fn parse_date_to_epoch(value: &str) -> Option<i64> {
        let mut parts = value.split('/');
        let day = parts.next()?.parse::<u32>().ok()?;
        let month = parts.next()?.parse::<u32>().ok()?;
        let year = parts.next()?.parse::<i32>().ok()?;
        if parts.next().is_some() || day == 0 || month == 0 || month > 12 || year < 1970 {
            return None;
        }
        let days = Self::days_from_civil(year, month, day)?;
        Some(days * 86_400)
    }

    fn days_from_civil(year: i32, month: u32, day: u32) -> Option<i64> {
        let leap = |y: i32| (y % 4 == 0 && y % 100 != 0) || (y % 400 == 0);
        let mdays = match month {
            1 => 31,
            2 => {
                if leap(year) {
                    29
                } else {
                    28
                }
            }
            3 => 31,
            4 => 30,
            5 => 31,
            6 => 30,
            7 => 31,
            8 => 31,
            9 => 30,
            10 => 31,
            11 => 30,
            12 => 31,
            _ => return None,
        };
        if day == 0 || day > mdays {
            return None;
        }
        let y = year - ((month <= 2) as i32);
        let era = if y >= 0 { y } else { y - 399 } / 400;
        let yoe = y - era * 400;
        let mp = month as i32 + if month > 2 { -3 } else { 9 };
        let doy = (153 * mp + 2) / 5 + day as i32 - 1;
        let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
        Some((era as i64) * 146097 + (doe as i64) - 719468)
    }

    fn print_banner(&self) {
        eprintln!("{} {}, {}", self.my_name, VERSION, SUBJECT);
        eprintln!(
            "{} {} {} {} {}",
            self.my_name, COPYRIGHT, self.provider.f, self.provider.s, self.provider.e
        );
    }

    pub fn parse_an_arg(&mut self, args: &[String], index: &mut usize) -> Result<bool, ShcError> {
        if *index >= args.len() {
            if self.file.is_none() {
                eprintln!("{} parse(-f): No source file specified", self.my_name);
                self.file = Some(String::new());
                return Err(ShcError::InvalidArgs("missing source file".to_string()));
            }
            return Ok(false);
        }

        let arg = &args[*index];
        match arg.as_str() {
            "-e" => {
                *index += 1;
                let value = args
                    .get(*index)
                    .ok_or_else(|| {
                        eprintln!("{} parse: Missing parameter", self.my_name);
                        ShcError::InvalidArgs("missing -e parameter".to_string())
                    })?
                    .clone();
                let expdate = Self::parse_date_to_epoch(&value).ok_or_else(|| {
                    eprintln!("{} parse(-e {}): Not a valid value", self.my_name, value);
                    ShcError::InvalidArgs(format!("invalid -e value: {value}"))
                })?;
                self.date = expdate.to_string();
                if self.verbose > 0 {
                    eprintln!("{} -e {}", self.my_name, self.date);
                }
            }
            "-m" => {
                *index += 1;
                self.mail = args.get(*index).cloned().ok_or_else(|| {
                    eprintln!("{} parse: Missing parameter", self.my_name);
                    ShcError::InvalidArgs("missing -m parameter".to_string())
                })?;
            }
            "-f" => {
                *index += 1;
                let value = args.get(*index).cloned().ok_or_else(|| {
                    eprintln!("{} parse: Missing parameter", self.my_name);
                    ShcError::InvalidArgs("missing -f parameter".to_string())
                })?;
                if self.file.is_some() {
                    eprintln!("{} parse(-f): Specified more than once", self.my_name);
                    return Err(ShcError::InvalidArgs("file specified more than once".to_string()));
                }
                self.file = Some(value);
            }
            "-i" => {
                *index += 1;
                self.inlo = Some(args.get(*index).cloned().ok_or_else(|| {
                    eprintln!("{} parse: Missing parameter", self.my_name);
                    ShcError::InvalidArgs("missing -i parameter".to_string())
                })?);
            }
            "-x" => {
                *index += 1;
                self.xecc = Some(args.get(*index).cloned().ok_or_else(|| {
                    eprintln!("{} parse: Missing parameter", self.my_name);
                    ShcError::InvalidArgs("missing -x parameter".to_string())
                })?);
            }
            "-l" => {
                *index += 1;
                self.lsto = Some(args.get(*index).cloned().ok_or_else(|| {
                    eprintln!("{} parse: Missing parameter", self.my_name);
                    ShcError::InvalidArgs("missing -l parameter".to_string())
                })?);
            }
            "-o" => {
                *index += 1;
                self.file2 = Some(args.get(*index).cloned().ok_or_else(|| {
                    eprintln!("{} parse: Missing parameter", self.my_name);
                    ShcError::InvalidArgs("missing -o parameter".to_string())
                })?);
            }
            "-r" => self.rlax[0] = self.rlax[0].wrapping_add(1),
            "-v" => self.verbose += 1,
            "-S" => self.setuid_flag = 1,
            "-D" => self.debugexec_flag = 1,
            "-U" => self.traceable_flag = 0,
            "-H" => self.hardening_flag = 1,
            "-B" => self.busyboxon_flag = 1,
            "-2" => self.mmap2_flag = 1,
            "-C" => {
                self.print_banner();
                eprintln!("{} ", self.my_name);
                for line in COPYING {
                    eprintln!("{line}");
                }
                eprintln!(
                    "    {} {} {}\n",
                    self.provider.f, self.provider.s, self.provider.e
                );
                return Err(ShcError::EarlyExit(0));
            }
            "-A" => {
                self.print_banner();
                eprintln!("{} ", self.my_name);
                for line in ABSTRACT {
                    eprintln!("{line}");
                }
                return Err(ShcError::EarlyExit(0));
            }
            "-h" => {
                self.print_banner();
                eprintln!("{} {}", self.my_name, USAGE);
                for line in HELP {
                    eprintln!("{line}");
                }
                return Err(ShcError::EarlyExit(0));
            }
            _ if arg.starts_with('-') => {
                eprintln!("{} parse: Unknown option", self.my_name);
                return Err(ShcError::InvalidArgs(format!("unknown option: {arg}")));
            }
            _ => {
                if self.file.is_none() {
                    self.file = Some(arg.clone());
                } else {
                    eprintln!("{} parse: Unknown option", self.my_name);
                    return Err(ShcError::InvalidArgs(format!("unexpected argument: {arg}")));
                }
            }
        }

        *index += 1;
        Ok(true)
    }

    pub fn parse_args(&mut self, args: &[String]) -> Result<(), ShcError> {
        if let Some(name) = args.first() {
            self.my_name = Path::new(name)
                .file_name()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_else(|| name.clone());
        }

        let mut err = 0usize;
        let mut index = 1usize;

        loop {
            match self.parse_an_arg(args, &mut index) {
                Ok(true) => {}
                Ok(false) => break,
                Err(ShcError::EarlyExit(code)) => return Err(ShcError::EarlyExit(code)),
                Err(e) => {
                    err += 1;
                    if index >= args.len() {
                        break;
                    }
                    index += 1;
                    if matches!(e, ShcError::InvalidArgs(_)) && index > args.len() {
                        break;
                    }
                }
            }
            if index > args.len() {
                break;
            }
        }

        if err > 0 {
            eprintln!("\n{} {}\n", self.my_name, USAGE);
            return Err(ShcError::InvalidArgs("argument parsing failed".to_string()));
        }

        if self.file.is_none() {
            eprintln!("{} parse(-f): No source file specified", self.my_name);
            eprintln!("\n{} {}\n", self.my_name, USAGE);
            return Err(ShcError::InvalidArgs("missing source file".to_string()));
        }

        Ok(())
    }

    pub fn stte_0(&mut self) {
        self.arc4.indx = 0;
        self.arc4.jndx = 0;
        self.arc4.kndx = 0;
        for (i, v) in self.arc4.stte.iter_mut().enumerate() {
            *v = i as u8;
        }
    }

    pub fn key(&mut self, data: &[u8]) {
        let mut len = data.len();
        let mut base = 0usize;

        while len > 0 {
            loop {
                let idx = self.arc4.indx as usize;
                let tmp = self.arc4.stte[idx];
                self.arc4.kndx = self.arc4.kndx.wrapping_add(tmp);
                self.arc4.kndx = self
                    .arc4
                    .kndx
                    .wrapping_add(data[base + idx % len]);
                let k = self.arc4.kndx as usize;
                self.arc4.stte[idx] = self.arc4.stte[k];
                self.arc4.stte[k] = tmp;
                self.arc4.indx = self.arc4.indx.wrapping_add(1);
                if self.arc4.indx == 0 {
                    break;
                }
            }
            let step = len.min(256);
            base += step;
            len -= step;
        }
    }

    pub fn arc_4(&mut self, data: &mut [u8]) {
        for byte in data.iter_mut() {
            self.arc4.indx = self.arc4.indx.wrapping_add(1);
            let idx = self.arc4.indx as usize;
            let mut tmp = self.arc4.stte[idx];
            self.arc4.jndx = self.arc4.jndx.wrapping_add(tmp);
            let j = self.arc4.jndx as usize;
            self.arc4.stte[idx] = self.arc4.stte[j];
            self.arc4.stte[j] = tmp;
            tmp = tmp.wrapping_add(self.arc4.stte[idx]);
            *byte ^= self.arc4.stte[tmp as usize];
        }
    }

    pub fn key_with_file(&mut self, path: impl AsRef<Path>) -> Result<(), ShcError> {
        let meta = fs::metadata(path.as_ref())?;
        let mut control = Vec::new();

        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            control.extend_from_slice(&meta.ino().to_ne_bytes());
            control.extend_from_slice(&meta.dev().to_ne_bytes());
            control.extend_from_slice(&meta.rdev().to_ne_bytes());
            control.extend_from_slice(&meta.uid().to_ne_bytes());
            control.extend_from_slice(&meta.gid().to_ne_bytes());
            control.extend_from_slice(&meta.size().to_ne_bytes());
            control.extend_from_slice(&meta.mtime().to_ne_bytes());
            control.extend_from_slice(&meta.ctime().to_ne_bytes());
        }

        #[cfg(not(unix))]
        {
            control.extend_from_slice(&meta.len().to_ne_bytes());
            if let Ok(modified) = meta.modified() {
                if let Ok(d) = modified.duration_since(UNIX_EPOCH) {
                    control.extend_from_slice(&d.as_secs().to_ne_bytes());
                    control.extend_from_slice(&d.subsec_nanos().to_ne_bytes());
                }
            }
            if let Ok(created) = meta.created() {
                if let Ok(d) = created.duration_since(UNIX_EPOCH) {
                    control.extend_from_slice(&d.as_secs().to_ne_bytes());
                    control.extend_from_slice(&d.subsec_nanos().to_ne_bytes());
                }
            }
        }

        self.key(&control);
        Ok(())
    }

    pub fn eval_shell(&mut self, text: &[u8]) -> Result<(), ShcError> {
        let line_end = text.iter().position(|b| *b == b'\n').unwrap_or(text.len());
        let first_line = String::from_utf8_lossy(&text[..line_end]).to_string();

        let trimmed = first_line.trim_start();
        if !trimmed.starts_with("#!") {
            eprintln!(
                "{}: invalid first line in script: {}",
                self.my_name, first_line
            );
            return Err(ShcError::InvalidData("invalid first line".to_string()));
        }

        let after = trimmed[2..].trim();
        let mut parts = after.split_whitespace();
        let shell_path = parts
            .next()
            .ok_or_else(|| {
                eprintln!(
                    "{}: invalid first line in script: {}",
                    self.my_name, first_line
                );
                ShcError::InvalidData("missing shell path".to_string())
            })?
            .to_string();

        let opts = parts.next().unwrap_or("").to_string();
        self.shll = Some(shell_path.clone());
        self.opts = opts;

        let shell_name = Path::new(&shell_path)
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .ok_or_else(|| {
                eprintln!("{}: invalid shll", self.my_name);
                ShcError::InvalidData("invalid shell".to_string())
            })?;

        if self.verbose > 0 {
            eprintln!("{} shll={}", self.my_name, shell_name);
        }

        for entry in Self::shells_db() {
            if shell_name == entry.shll {
                if self.inlo.is_none() {
                    self.inlo = Some(entry.inlo.to_string());
                }
                if self.xecc.is_none() {
                    self.xecc = Some(entry.xecc.to_string());
                }
                if self.lsto.is_none() {
                    self.lsto = Some(entry.lsto.to_string());
                }
            }
        }

        if self.inlo.is_none() || self.xecc.is_none() || self.lsto.is_none() {
            eprintln!(
                "{} Unknown shell ({}): specify [-i][-x][-l]",
                self.my_name, shell_name
            );
            return Err(ShcError::InvalidData("unknown shell".to_string()));
        }

        if self.verbose > 0 {
            eprintln!(
                "{} [-i]={}",
                self.my_name,
                self.inlo.as_deref().unwrap_or("")
            );
            eprintln!(
                "{} [-x]={}",
                self.my_name,
                self.xecc.as_deref().unwrap_or("")
            );
            eprintln!(
                "{} [-l]={}",
                self.my_name,
                self.lsto.as_deref().unwrap_or("")
            );
        }

        if !self.opts.is_empty() && self.opts == self.lsto.as_deref().unwrap_or("") {
            eprintln!(
                "{} opts={} : Is equal to [-l]. Removing opts",
                self.my_name, self.opts
            );
            self.opts.clear();
        } else if self.opts == "-" {
            eprintln!(
                "{} opts={} : No real one. Removing opts",
                self.my_name, self.opts
            );
            self.opts.clear();
        }

        if self.verbose > 0 {
            eprintln!("{} opts={}", self.my_name, self.opts);
        }

        Ok(())
    }

    pub fn read_script(&self, path: impl AsRef<Path>) -> Result<Vec<u8>, ShcError> {
        let path_ref = path.as_ref();
        let text = fs::read(path_ref)?;
        let mut with_nul = text;
        if !with_nul.ends_with(&[0]) {
            with_nul.push(0);
        }

        let arg_max = 2_097_152usize;
        let l = with_nul.len().saturating_sub(1);
        if (l as f64) > 0.80 * (arg_max as f64) {
            eprintln!(
                "{}: WARNING!!\n   Scripts of length near to (or higher than) the current System limit on\n   \"maximum size of arguments to EXEC\", could comprise its binary execution.\n   In the current System the call sysconf(_SC_ARG_MAX) returns {} bytes\n   and your script \"{}\" is {} bytes length.",
                self.my_name,
                arg_max,
                path_ref.display(),
                l
            );
        }

        Ok(with_nul)
    }

    fn next_rand_u32(&mut self) -> u32 {
        self.rand_state = self
            .rand_state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1);
        (self.rand_state >> 32) as u32
    }

    pub fn rand_mod(&mut self, modulus: usize) -> usize {
        if modulus == 0 {
            return 0;
        }
        let mut top = u32::MAX as u64;
        top -= top % modulus as u64;
        let rnd = loop {
            let candidate = self.next_rand_u32() as u64;
            if candidate < top {
                break candidate;
            }
        };
        ((modulus as f64) * (rnd as f64) / (1.0 + top as f64)) as usize
    }

    pub fn rand_chr(&mut self) -> u8 {
        self.rand_mod(1usize << 8) as u8
    }

    pub fn noise(&mut self, buf: &mut [u8], min: usize, xtra: usize, string_mode: bool) -> usize {
        let mut total = min;
        if xtra != 0 {
            total += self.rand_mod(xtra);
        }

        let write_len = total.min(buf.len().saturating_sub(usize::from(string_mode)));
        for slot in buf.iter_mut().take(write_len) {
            loop {
                *slot = self.rand_chr();
                if !string_mode || (*slot as char).is_ascii_alphanumeric() {
                    break;
                }
            }
        }
        if string_mode && write_len < buf.len() {
            buf[write_len] = 0;
        }
        write_len
    }

    pub fn prnt_bytes<W: Write>(
        &mut self,
        out: &mut W,
        ptr: &[u8],
        m: usize,
        l: usize,
        n: usize,
    ) -> Result<(), ShcError> {
        let l2 = l + m;
        let n2 = n + l2;
        let mut i = 0usize;
        while i < n2 {
            if (i & 0xf) == 0 {
                write!(out, "\n\t\"")?;
            }
            let byte = if i >= m && i < l2 {
                ptr[i - m]
            } else {
                self.rand_chr()
            };
            write!(out, "\\{:03o}", byte)?;
            if (i & 0xf) == 0xf {
                write!(out, "\"")?;
            }
            i += 1;
        }
        if (i & 0xf) != 0 {
            write!(out, "\"")?;
        }
        self.offset += n2;
        Ok(())
    }

    pub fn prnt_array<W: Write>(
        &mut self,
        out: &mut W,
        ptr: &[u8],
        name: &str,
        l: usize,
        cast: Option<&str>,
    ) -> Result<(), ShcError> {
        let mut m = self.rand_mod(1 + l / 4);
        let n = self.rand_mod(1 + l / 4);
        let a = (self.offset + m) % l.max(1);
        if cast.is_some() && a != 0 {
            m += l - a;
        }
        write!(out, "\n")?;
        write!(out, "#define      {name}_z\t{l}")?;
        write!(out, "\n")?;
        write!(
            out,
            "#define      {name}\t({}(&data[{}]))",
            cast.unwrap_or(""),
            self.offset + m
        )?;
        self.prnt_bytes(out, ptr, m, l, n)
    }

    pub fn dump_array<W: Write>(
        &mut self,
        out: &mut W,
        ptr: &mut [u8],
        name: &str,
        l: usize,
        cast: Option<&str>,
    ) -> Result<(), ShcError> {
        let len = l.min(ptr.len());
        self.arc_4(&mut ptr[..len]);
        self.prnt_array(out, &ptr[..len], name, len, cast)
    }

    pub fn write_c(&mut self, file: &str, argv: &[String]) -> Result<(), ShcError> {
        let mut pswd = vec![0u8; 256];
        let mut pswd_z = pswd.len();

        let mut msg1 = b"has expired!\n".to_vec();
        let mut date = self.date.clone().into_bytes();
        date.push(0);

        let shll_src = self
            .shll
            .clone()
            .ok_or_else(|| ShcError::InvalidData("missing shell".to_string()))?;
        let mut kwsh = shll_src.clone().into_bytes();
        kwsh.push(0);

        let mut shll = shll_src.into_bytes();
        shll.push(0);

        let mut inlo = self
            .inlo
            .clone()
            .ok_or_else(|| ShcError::InvalidData("missing inlo".to_string()))?
            .into_bytes();
        inlo.push(0);

        let mut xecc = self
            .xecc
            .clone()
            .ok_or_else(|| ShcError::InvalidData("missing xecc".to_string()))?
            .into_bytes();
        xecc.push(0);

        let mut lsto = self
            .lsto
            .clone()
            .ok_or_else(|| ShcError::InvalidData("missing lsto".to_string()))?
            .into_bytes();
        lsto.push(0);

        let mut tst1 = b"location has changed!".to_vec();
        tst1.push(0);
        let mut chk1 = tst1.clone();

        let mut msg2 = b"abnormal behavior!".to_vec();
        msg2.push(0);

        let mut rlax = self.rlax.to_vec();

        let mut opts = self.opts.clone().into_bytes();
        opts.push(0);

        let mut text = self
            .text
            .clone()
            .ok_or_else(|| ShcError::InvalidData("missing script text".to_string()))?;

        let mut tst2 = b"shell has changed!".to_vec();
        tst2.push(0);
        let mut chk2 = tst2.clone();

        self.offset = 0;

        pswd_z = self.noise(&mut pswd, pswd_z, 0, false);
        let mut numd = 0i32;
        numd += 1;

        self.stte_0();
        self.key(&pswd[..pswd_z]);

        msg1.extend_from_slice(self.mail.as_bytes());
        msg1.push(0);
        self.arc_4(&mut msg1);
        numd += 1;

        self.arc_4(&mut date);
        numd += 1;
        self.arc_4(&mut shll);
        numd += 1;
        self.arc_4(&mut inlo);
        numd += 1;
        self.arc_4(&mut xecc);
        numd += 1;
        self.arc_4(&mut lsto);
        numd += 1;
        self.arc_4(&mut tst1);
        numd += 1;

        self.key(&chk1);
        self.arc_4(&mut chk1);
        numd += 1;

        self.arc_4(&mut msg2);
        numd += 1;

        let indx = self.rlax[0] == 0;
        self.arc_4(&mut rlax);
        numd += 1;

        if indx {
            let shell_path = String::from_utf8_lossy(&kwsh[..kwsh.len().saturating_sub(1)]).to_string();
            if let Err(e) = self.key_with_file(&shell_path) {
                eprintln!("{}: invalid file name: {} {}", self.my_name, shell_path, e);
                return Err(ShcError::InvalidData(format!("invalid file name: {shell_path}")));
            }
        }

        self.arc_4(&mut opts);
        numd += 1;
        self.arc_4(&mut text);
        numd += 1;
        self.arc_4(&mut tst2);
        numd += 1;

        self.key(&chk2);
        self.arc_4(&mut chk2);
        numd += 1;

        let out_name = format!("{file}.x.c");
        let mut out = File::create(&out_name)?;

        writeln!(out, "#if 0")?;
        writeln!(out, "\t{} {}, {}", self.my_name, VERSION, SUBJECT)?;
        writeln!(
            out,
            "\t{} {} {} {}\n",
            COPYRIGHT, self.provider.f, self.provider.s, self.provider.e
        )?;
        write!(out, "\t")?;
        for arg in argv {
            write!(out, "{arg} ")?;
        }
        writeln!(out, "\n#endif\n")?;
        write!(out, "static  char data [] = ")?;

        let mut entries: Vec<(&str, Vec<u8>)> = vec![
            ("pswd", pswd[..pswd_z].to_vec()),
            ("msg1", msg1),
            ("date", date),
            ("shll", shll),
            ("inlo", inlo),
            ("xecc", xecc),
            ("lsto", lsto),
            ("tst1", tst1),
            ("chk1", chk1),
            ("msg2", msg2),
            ("rlax", rlax),
            ("opts", opts),
            ("text", text),
            ("tst2", tst2),
            ("chk2", chk2),
        ];

        while numd > 0 {
            let idx = self.rand_mod(entries.len());
            let (name, data) = entries.remove(idx);
            self.prnt_array(&mut out, &data, name, data.len(), None)?;
            numd -= 1;
        }

        writeln!(out, "/* End of data[] */;")?;
        writeln!(out, "#define      hide_z\t{}", 1 << 12)?;
        write!(out, "{}", Self::render_define_i32(SETUID_LINE, self.setuid_flag))?;
        write!(
            out,
            "{}",
            Self::render_define_i32(DEBUGEXEC_LINE, self.debugexec_flag)
        )?;
        write!(
            out,
            "{}",
            Self::render_define_i32(TRACEABLE_LINE, self.traceable_flag)
        )?;
        write!(
            out,
            "{}",
            Self::render_define_i32(HARDENING_LINE, self.hardening_flag)
        )?;
        write!(
            out,
            "{}",
            Self::render_define_i32(BUSYBOXON_LINE, self.busyboxon_flag)
        )?;
        write!(out, "{}", Self::render_define_i32(MMAP2_LINE, self.mmap2_flag))?;
        for line in RTC {
            writeln!(out, "{line}")?;
        }
        out.flush()?;

        Ok(())
    }

    pub fn make(&mut self) -> Result<(), ShcError> {
        let file = self
            .file
            .clone()
            .ok_or_else(|| ShcError::InvalidData("missing source file".to_string()))?;
        if self.file2.is_none() {
            self.file2 = Some(format!("{file}.x"));
        }
        let out = self.file2.clone().unwrap_or_default();

        let cc = env::var("CC").unwrap_or_else(|_| "cc".to_string());
        let cflags = env::var("CFLAGS").unwrap_or_default();
        let ldflags = env::var("LDFLAGS").unwrap_or_default();

        let mut cmd = format!("{cc} {cflags} {ldflags} {file}.x.c -o {out}");
        if self.verbose > 0 {
            eprintln!("{}: {}", self.my_name, cmd);
        }
        let status = Command::new("sh").arg("-c").arg(&cmd).status()?;
        if !status.success() {
            return Err(ShcError::ProcessFailed(cmd));
        }

        let strip = env::var("STRIP").unwrap_or_else(|_| "strip".to_string());
        cmd = format!("{strip} {out}");
        if self.verbose > 0 {
            eprintln!("{}: {}", self.my_name, cmd);
        }
        let status = Command::new("sh").arg("-c").arg(&cmd).status()?;
        if !status.success() {
            eprintln!("{}: never mind", self.my_name);
        }

        cmd = format!("chmod ug=rwx,o=rx {out}");
        if self.verbose > 0 {
            eprintln!("{}: {}", self.my_name, cmd);
        }
        let status = Command::new("sh").arg("-c").arg(&cmd).status()?;
        if !status.success() {
            eprintln!("{}: remove read permission", self.my_name);
        }

        Ok(())
    }
pub fn do_all(&mut self, args: &[String]) -> Result<(), ShcError> {
        self.parse_args(args)?;
        let file = self
            .file
            .clone()
            .ok_or_else(|| ShcError::InvalidArgs("missing source file".to_string()))?;
        let text = self.read_script(&file)?;
        self.text = Some(text.clone());
        self.eval_shell(&text)?;
        self.write_c(&file, args)?;
        self.make()?;
        Ok(())
    }

    pub fn main(&mut self, args: &[String]) -> ExitCode {
        match self.do_all(args) {
            Ok(()) => ExitCode::SUCCESS,
            Err(ShcError::EarlyExit(code)) => ExitCode::from(code.clamp(0, 255) as u8),
            Err(err) => {
                eprintln!("{err}");
                ExitCode::from(1)
            }
        }
    }

    pub fn module_src() -> &'static str {
        include_str!("shc.rs")
    }
}
