use std::io::{self, Write};

use crate::dot::{OutputCommand, OutputSymbol};
use crate::output::{OutputDriver, RenderedSymbol};

pub struct Gnu;

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct HandlerData {
    emacs_mode: bool,
    package_string: Option<String>,
    brief_listing: bool,
    print_as_tree: bool,
}

impl HandlerData {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_emacs_mode(mut self, enabled: bool) -> Self {
        self.emacs_mode = enabled;
        self
    }

    pub fn with_package_string(mut self, package: impl Into<String>) -> Self {
        self.package_string = Some(package.into());
        self
    }

    pub fn with_brief_listing(mut self, enabled: bool) -> Self {
        self.brief_listing = enabled;
        self
    }

    pub fn with_tree_mode(mut self, enabled: bool) -> Self {
        self.print_as_tree = enabled;
        self
    }
}

impl Gnu {
    pub fn handler_data() -> HandlerData {
        HandlerData::default()
    }

    pub fn print_function_name<W: Write>(
        writer: &mut W,
        symbol: &OutputSymbol,
        has_subtree: bool,
        handler_data: &HandlerData,
    ) -> io::Result<()> {
        write!(writer, "{}", symbol.name)?;

        if symbol.declaration.is_some() {
            write!(writer, "()")?;
        }

        if let (Some(decl), Some(source), Some(def_line)) = (
            symbol.declaration.as_deref(),
            symbol.source.as_deref(),
            symbol.definition_line,
        ) {
            write!(writer, " <{} at {}:{}>", decl, source, def_line)?;
        }

        if symbol.active {
            if let Some(expand_line) = symbol.expand_line {
                write!(writer, " (recursive: see {})", expand_line.saturating_sub(1))?;
            } else {
                write!(writer, " (recursive)")?;
            }
            return Ok(());
        }


        if !handler_data.print_as_tree && has_subtree {
            write!(writer, ":")?;
        }

        Ok(())
    }

    pub fn print_symbol<W: Write>(
        writer: &mut W,
        line: i32,
        symbol: &mut OutputSymbol,
        handler_data: &HandlerData,
    ) -> io::Result<bool> {
        let has_subtree = if symbol.direct {
            !symbol.callee.is_empty()
        } else {
            !symbol.caller.is_empty()
        };

        for _ in 0..symbol.expand_line.unwrap_or(0).max(0) {
            write!(writer, "  ")?;
        }

        Self::print_function_name(writer, symbol, has_subtree, handler_data)?;

        if handler_data.brief_listing {
            if let Some(expand_line) = symbol.expand_line {
                write!(writer, " [see {}]", expand_line)?;
                return Ok(true);
            } else if !symbol.callee.is_empty() {
                symbol.expand_line = Some(line);
            }
        }

        Ok(false)
    }

    pub fn output_handler<W: Write>(
        writer: &mut W,
        command: OutputCommand,
        line: i32,
        text: Option<&str>,
        symbol: Option<&mut OutputSymbol>,
        handler_data: &HandlerData,
    ) -> io::Result<bool> {
        match command {
            OutputCommand::Begin => {
                if handler_data.emacs_mode {
                    let package = handler_data.package_string.as_deref().unwrap_or("");
                    write!(
                        writer,
                        ";; This file is generated by {}. -*- cflow -*-",
                        package
                    )?;
                    writeln!(writer)?;
                }
                Ok(false)
            }
            OutputCommand::Init
            | OutputCommand::End
            | OutputCommand::Separator
            | OutputCommand::Other => Ok(false),
            OutputCommand::Newline => {
                writeln!(writer)?;
                Ok(false)
            }
            OutputCommand::Text => {
                if let Some(text) = text {
                    write!(writer, "{}", text)?;
                }
                Ok(false)
            }
            OutputCommand::Symbol => {
                if let Some(symbol) = symbol {
                    Self::print_symbol(writer, line, symbol, handler_data)
                } else {
                    Ok(false)
                }
            }
        }
    }

    pub fn new() -> Self {
        Gnu
    }
}

impl OutputDriver for Gnu {
    fn begin(&mut self, _writer: &mut dyn Write, _line: usize) -> io::Result<()> {
        Ok(())
    }

    fn separator(&mut self, _writer: &mut dyn Write, _line: usize) -> io::Result<()> {
        Ok(())
    }

    fn symbol(
        &mut self,
        writer: &mut dyn Write,
        line: usize,
        symbol: &RenderedSymbol<'_>,
    ) -> io::Result<bool> {
        let has_subtree = if symbol.direct {
            !symbol.symbol.callee.is_empty()
        } else {
            !symbol.symbol.caller.is_empty()
        };

        write!(writer, "{}", symbol.symbol.name)?;

        if symbol.symbol.decl.is_some() {
            write!(writer, "()")?;
        }

        if let (Some(decl), Some(source)) = (
            symbol.symbol.decl.as_deref(),
            symbol.symbol.source.as_deref(),
        ) {
            write!(writer, " <{} at {}:{}>", decl, source, symbol.symbol.def_line)?;
        }

        if symbol.symbol.active != 0 {
            write!(writer, " (recursive)")?;
            return Ok(true);
        }

        if has_subtree {
            write!(writer, ":")?;
        }

        let _ = line;
        Ok(false)
    }
}
